package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * $table.ViewName Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "CREDIT_TBL")
public class Credit {
	public static final String TABLE_NAME = "CREDIT_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String CreditId = "CreditId";
	public static final String DetailId = "DetailId";
	public static final String PaymentDate = "PaymentDate";
	public static final String CreditAmount = "CreditAmount";
	public static final String TradingNo = "TradingNo";
	public static final String Note = "Note";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "CREDIT_ID", length = 0, nullable = false)
	private Long creditId;

	/* 見積詳細 */
	@Column(name = "DETAIL_ID", length = 0, nullable = true)
	@JoinTable(name = "EstmationDetail")
	@JoinColumn(name = "DetailId")
	private Long detailId;

	/*  */
	@Column(name = "PAYMENT_DATE", length = 8, nullable = true)
	private String paymentDate;

	/*  */
	@Column(name = "CREDIT_AMOUNT", length = 0, nullable = true)
	private Money creditAmount;

	/* 発貨一覧の取引No */
	@Column(name = "TRADING_NO", length = 64, nullable = true)
	private String tradingNo;

	/* 発貨一覧の備考 */
	@Column(name = "NOTE", length = 64, nullable = true)
	private String note;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getCreditId() {
		return creditId;
	}

	/*
	 * Set the value of
	 * 
	 * @param creditId the new value for $col.ViewName
	 */
	public void setCreditId(Long creditId) {
		this.creditId = creditId;
	}

	/*
	 * Get the 見積詳細
	 * 
	 * @return the value of 見積詳細
	 */
	public Long getDetailId() {
		return detailId;
	}

	/*
	 * Set the value of 見積詳細
	 * 
	 * @param detailId the new value for 見積詳細
	 */
	public void setDetailId(Long detailId) {
		this.detailId = detailId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getPaymentDate() {
		return paymentDate;
	}

	/*
	 * Set the value of
	 * 
	 * @param paymentDate the new value for $col.ViewName
	 */
	public void setPaymentDate(String paymentDate) {
		this.paymentDate = paymentDate;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Money getCreditAmount() {
		return creditAmount;
	}

	/*
	 * Set the value of
	 * 
	 * @param creditAmount the new value for $col.ViewName
	 */
	public void setCreditAmount(Money creditAmount) {
		this.creditAmount = creditAmount;
	}

	/*
	 * Get the 発貨一覧の取引No
	 * 
	 * @return the value of 発貨一覧の取引No
	 */
	public String getTradingNo() {
		return tradingNo;
	}

	/*
	 * Set the value of 発貨一覧の取引No
	 * 
	 * @param tradingNo the new value for 発貨一覧の取引No
	 */
	public void setTradingNo(String tradingNo) {
		this.tradingNo = tradingNo;
	}

	/*
	 * Get the 発貨一覧の備考
	 * 
	 * @return the value of 発貨一覧の備考
	 */
	public String getNote() {
		return note;
	}

	/*
	 * Set the value of 発貨一覧の備考
	 * 
	 * @param note the new value for 発貨一覧の備考
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("CreditId");
		sb.append("=");
		sb.append(creditId);
		sb.append("\n");
		sb.append("\t");
		sb.append("DetailId");
		sb.append("=");
		sb.append(detailId);
		sb.append("\n");
		sb.append("\t");
		sb.append("PaymentDate");
		sb.append("=");
		sb.append(paymentDate);
		sb.append("\n");
		sb.append("\t");
		sb.append("CreditAmount");
		sb.append("=");
		sb.append(creditAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("TradingNo");
		sb.append("=");
		sb.append(tradingNo);
		sb.append("\n");
		sb.append("\t");
		sb.append("Note");
		sb.append("=");
		sb.append(note);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
