package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

/*
 * $table.ViewName Model
 *
 * This class was autogenerated on:
 * [Wed Aug 12 17:38:16 JST 2015]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ESTIMATION_CURRENCY_TBL")
public class EstimationCurrency {
	public static final String TABLE_NAME = "ESTIMATION_CURRENCY_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String EstimationDelivery = "EstimationDelivery";
	public static final String DeliveryId = "DeliveryId";
	public static final String EstimationId = "EstimationId";
	public static final String Type = "Type";
	public static final String Address = "Address";
	public static final String DeliveryDate = "DeliveryDate";
	public static final String Quantity = "Quantity";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "ESTIMATION_DELIVERY", length = 0, nullable = false)
	private Long estimationDelivery;

	/*  */
	@Column(name = "DELIVERY_ID", length = 0, nullable = false)
	private Long deliveryId;

	/*  */
	@Column(name = "ESTIMATION_ID", length = 0, nullable = false)
	@JoinTable(name = "EstmationSheet")
	@JoinColumn(name = "EstimationId")
	private Long estimationId;

	/*  */
	@Column(name = "TYPE", length = 32, nullable = true)
	private String type;

	/*  */
	@Column(name = "ADDRESS", length = 32, nullable = true)
	private String address;

	/*  */
	@Column(name = "DELIVERY_DATE", length = 8, nullable = true)
	private String deliveryDate;

	/*  */
	@Column(name = "QUANTITY", length = 0, nullable = true)
	private Integer quantity;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getEstimationDelivery() {
		return estimationDelivery;
	}

	/*
	 * Set the value of
	 * 
	 * @param estimationDelivery the new value for $col.ViewName
	 */
	public void setEstimationDelivery(Long estimationDelivery) {
		this.estimationDelivery = estimationDelivery;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getDeliveryId() {
		return deliveryId;
	}

	/*
	 * Set the value of
	 * 
	 * @param deliveryId the new value for $col.ViewName
	 */
	public void setDeliveryId(Long deliveryId) {
		this.deliveryId = deliveryId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getEstimationId() {
		return estimationId;
	}

	/*
	 * Set the value of
	 * 
	 * @param estimationId the new value for $col.ViewName
	 */
	public void setEstimationId(Long estimationId) {
		this.estimationId = estimationId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getType() {
		return type;
	}

	/*
	 * Set the value of
	 * 
	 * @param type the new value for $col.ViewName
	 */
	public void setType(String type) {
		this.type = type;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getAddress() {
		return address;
	}

	/*
	 * Set the value of
	 * 
	 * @param address the new value for $col.ViewName
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getDeliveryDate() {
		return deliveryDate;
	}

	/*
	 * Set the value of
	 * 
	 * @param deliveryDate the new value for $col.ViewName
	 */
	public void setDeliveryDate(String deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/*
	 * Set the value of
	 * 
	 * @param quantity the new value for $col.ViewName
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("EstimationDelivery");
		sb.append("=");
		sb.append(estimationDelivery);
		sb.append("\n");
		sb.append("\t");
		sb.append("DeliveryId");
		sb.append("=");
		sb.append(deliveryId);
		sb.append("\n");
		sb.append("\t");
		sb.append("EstimationId");
		sb.append("=");
		sb.append(estimationId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Type");
		sb.append("=");
		sb.append(type);
		sb.append("\n");
		sb.append("\t");
		sb.append("Address");
		sb.append("=");
		sb.append(address);
		sb.append("\n");
		sb.append("\t");
		sb.append("DeliveryDate");
		sb.append("=");
		sb.append(deliveryDate);
		sb.append("\n");
		sb.append("\t");
		sb.append("Quantity");
		sb.append("=");
		sb.append(quantity);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
