package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

/*
 * $table.ViewName Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ESTIMATION_ACCEPT_TBL")
public class EstimationAccept {
	public static final String TABLE_NAME = "ESTIMATION_ACCEPT_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String AcceptId = "AcceptId";
	public static final String DetailId = "DetailId";
	public static final String Date = "Date";
	public static final String TradingNo = "TradingNo";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "ACCEPT_ID", length = 0, nullable = false)
	private Long acceptId;

	/* 見積詳細 */
	@Column(name = "DETAIL_ID", length = 0, nullable = false)
	@JoinTable(name = "EstmationDetail")
	@JoinColumn(name = "DetailId")
	private Long detailId;

	/* 売上日付 */
	@Column(name = "DATE", length = 8, nullable = true)
	private String date;

	/* 取引No */
	@Column(name = "TRADING_NO", length = 64, nullable = true)
	private String tradingNo;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getAcceptId() {
		return acceptId;
	}

	/*
	 * Set the value of
	 * 
	 * @param acceptId the new value for $col.ViewName
	 */
	public void setAcceptId(Long acceptId) {
		this.acceptId = acceptId;
	}

	/*
	 * Get the 見積詳細
	 * 
	 * @return the value of 見積詳細
	 */
	public Long getDetailId() {
		return detailId;
	}

	/*
	 * Set the value of 見積詳細
	 * 
	 * @param detailId the new value for 見積詳細
	 */
	public void setDetailId(Long detailId) {
		this.detailId = detailId;
	}

	/*
	 * Get the 売上日付
	 * 
	 * @return the value of 売上日付
	 */
	public String getDate() {
		return date;
	}

	/*
	 * Set the value of 売上日付
	 * 
	 * @param date the new value for 売上日付
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/*
	 * Get the 取引No
	 * 
	 * @return the value of 取引No
	 */
	public String getTradingNo() {
		return tradingNo;
	}

	/*
	 * Set the value of 取引No
	 * 
	 * @param tradingNo the new value for 取引No
	 */
	public void setTradingNo(String tradingNo) {
		this.tradingNo = tradingNo;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("AcceptId");
		sb.append("=");
		sb.append(acceptId);
		sb.append("\n");
		sb.append("\t");
		sb.append("DetailId");
		sb.append("=");
		sb.append(detailId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Date");
		sb.append("=");
		sb.append(date);
		sb.append("\n");
		sb.append("\t");
		sb.append("TradingNo");
		sb.append("=");
		sb.append(tradingNo);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
