package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * 商品マスタ Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ITEM_TBL")
public class Item {
	public static final String TABLE_NAME = "ITEM_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String ItemId = "ItemId";
	public static final String CategoryType = "CategoryType";
	public static final String Family = "Family";
	public static final String JpName = "JpName";
	public static final String CnName = "CnName";
	public static final String EnName = "EnName";
	public static final String PartsCd = "PartsCd";
	public static final String ModelCd = "ModelCd";
	public static final String JpDesc = "JpDesc";
	public static final String CnDesc = "CnDesc";
	public static final String EnDesc = "EnDesc";
	public static final String JpNameSearch = "JpNameSearch";
	public static final String CnNameSearch = "CnNameSearch";
	public static final String EnNameSearch = "EnNameSearch";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* 物品ID */
	@Column(name = "ITEM_ID", length = 0, nullable = false)
	private Long itemId;

	/* 大分類 */
	@Column(name = "CATEGORY_TYPE", length = 64, nullable = true)
	private String categoryType;

	/* 小分類 */
	@Column(name = "FAMILY", length = 64, nullable = true)
	private String family;

	/* 日文名 */
	@Column(name = "JP_NAME", length = 64, nullable = true)
	private String jpName;

	/* 中文名 */
	@Column(name = "CN_NAME", length = 64, nullable = true)
	private String cnName;

	/* 英文名 */
	@Column(name = "EN_NAME", length = 64, nullable = true)
	private String enName;

	/* 零件编号 */
	@Column(name = "PARTS_CD", length = 64, nullable = true)
	private String partsCd;

	/* 设备编号 */
	@Column(name = "MODEL_CD", length = 64, nullable = true)
	private String modelCd;

	/* 日文标签 */
	@Column(name = "JP_DESC", length = 512, nullable = true)
	private String jpDesc;

	/* 中文标签 */
	@Column(name = "CN_DESC", length = 512, nullable = true)
	private String cnDesc;

	/* 英文标签 */
	@Column(name = "EN_DESC", length = 512, nullable = true)
	private String enDesc;

	/* 日文名 */
	@Column(name = "JP_NAME_SEARCH", length = 576, nullable = true)
	private String jpNameSearch;

	/* 中文名 */
	@Column(name = "CN_NAME_SEARCH", length = 576, nullable = true)
	private String cnNameSearch;

	/* 英文名 */
	@Column(name = "EN_NAME_SEARCH", length = 576, nullable = true)
	private String enNameSearch;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the 物品ID
	 * 
	 * @return the value of 物品ID
	 */
	public Long getItemId() {
		return itemId;
	}

	/*
	 * Set the value of 物品ID
	 * 
	 * @param itemId the new value for 物品ID
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	/*
	 * Get the 大分類
	 * 
	 * @return the value of 大分類
	 */
	public String getCategoryType() {
		return categoryType;
	}

	/*
	 * Set the value of 大分類
	 * 
	 * @param categoryType the new value for 大分類
	 */
	public void setCategoryType(String categoryType) {
		this.categoryType = categoryType;
	}

	/*
	 * Get the 小分類
	 * 
	 * @return the value of 小分類
	 */
	public String getFamily() {
		return family;
	}

	/*
	 * Set the value of 小分類
	 * 
	 * @param family the new value for 小分類
	 */
	public void setFamily(String family) {
		this.family = family;
	}

	/*
	 * Get the 日文名
	 * 
	 * @return the value of 日文名
	 */
	public String getJpName() {
		return jpName;
	}

	/*
	 * Set the value of 日文名
	 * 
	 * @param jpName the new value for 日文名
	 */
	public void setJpName(String jpName) {
		this.jpName = jpName;
	}

	/*
	 * Get the 中文名
	 * 
	 * @return the value of 中文名
	 */
	public String getCnName() {
		return cnName;
	}

	/*
	 * Set the value of 中文名
	 * 
	 * @param cnName the new value for 中文名
	 */
	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	/*
	 * Get the 英文名
	 * 
	 * @return the value of 英文名
	 */
	public String getEnName() {
		return enName;
	}

	/*
	 * Set the value of 英文名
	 * 
	 * @param enName the new value for 英文名
	 */
	public void setEnName(String enName) {
		this.enName = enName;
	}

	/*
	 * Get the 零件编号
	 * 
	 * @return the value of 零件编号
	 */
	public String getPartsCd() {
		return partsCd;
	}

	/*
	 * Set the value of 零件编号
	 * 
	 * @param partsCd the new value for 零件编号
	 */
	public void setPartsCd(String partsCd) {
		this.partsCd = partsCd;
	}

	/*
	 * Get the 设备编号
	 * 
	 * @return the value of 设备编号
	 */
	public String getModelCd() {
		return modelCd;
	}

	/*
	 * Set the value of 设备编号
	 * 
	 * @param modelCd the new value for 设备编号
	 */
	public void setModelCd(String modelCd) {
		this.modelCd = modelCd;
	}

	/*
	 * Get the 日文标签
	 * 
	 * @return the value of 日文标签
	 */
	public String getJpDesc() {
		return jpDesc;
	}

	/*
	 * Set the value of 日文标签
	 * 
	 * @param jpDesc the new value for 日文标签
	 */
	public void setJpDesc(String jpDesc) {
		this.jpDesc = jpDesc;
	}

	/*
	 * Get the 中文标签
	 * 
	 * @return the value of 中文标签
	 */
	public String getCnDesc() {
		return cnDesc;
	}

	/*
	 * Set the value of 中文标签
	 * 
	 * @param cnDesc the new value for 中文标签
	 */
	public void setCnDesc(String cnDesc) {
		this.cnDesc = cnDesc;
	}

	/*
	 * Get the 英文标签
	 * 
	 * @return the value of 英文标签
	 */
	public String getEnDesc() {
		return enDesc;
	}

	/*
	 * Set the value of 英文标签
	 * 
	 * @param enDesc the new value for 英文标签
	 */
	public void setEnDesc(String enDesc) {
		this.enDesc = enDesc;
	}

	/*
	 * Get the 日文名
	 * 
	 * @return the value of 日文名
	 */
	public String getJpNameSearch() {
		return jpNameSearch;
	}

	/*
	 * Set the value of 日文名
	 * 
	 * @param jpNameSearch the new value for 日文名
	 */
	public void setJpNameSearch(String jpNameSearch) {
		this.jpNameSearch = jpNameSearch;
	}

	/*
	 * Get the 中文名
	 * 
	 * @return the value of 中文名
	 */
	public String getCnNameSearch() {
		return cnNameSearch;
	}

	/*
	 * Set the value of 中文名
	 * 
	 * @param cnNameSearch the new value for 中文名
	 */
	public void setCnNameSearch(String cnNameSearch) {
		this.cnNameSearch = cnNameSearch;
	}

	/*
	 * Get the 英文名
	 * 
	 * @return the value of 英文名
	 */
	public String getEnNameSearch() {
		return enNameSearch;
	}

	/*
	 * Set the value of 英文名
	 * 
	 * @param enNameSearch the new value for 英文名
	 */
	public void setEnNameSearch(String enNameSearch) {
		this.enNameSearch = enNameSearch;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("ItemId");
		sb.append("=");
		sb.append(itemId);
		sb.append("\n");
		sb.append("\t");
		sb.append("CategoryType");
		sb.append("=");
		sb.append(categoryType);
		sb.append("\n");
		sb.append("\t");
		sb.append("Family");
		sb.append("=");
		sb.append(family);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpName");
		sb.append("=");
		sb.append(jpName);
		sb.append("\n");
		sb.append("\t");
		sb.append("CnName");
		sb.append("=");
		sb.append(cnName);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnName");
		sb.append("=");
		sb.append(enName);
		sb.append("\n");
		sb.append("\t");
		sb.append("PartsCd");
		sb.append("=");
		sb.append(partsCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("ModelCd");
		sb.append("=");
		sb.append(modelCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpDesc");
		sb.append("=");
		sb.append(jpDesc);
		sb.append("\n");
		sb.append("\t");
		sb.append("CnDesc");
		sb.append("=");
		sb.append(cnDesc);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnDesc");
		sb.append("=");
		sb.append(enDesc);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpNameSearch");
		sb.append("=");
		sb.append(jpNameSearch);
		sb.append("\n");
		sb.append("\t");
		sb.append("CnNameSearch");
		sb.append("=");
		sb.append(cnNameSearch);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnNameSearch");
		sb.append("=");
		sb.append(enNameSearch);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
