package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

/*
 * 加盟店マスタ Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "NAPA_STORES_TBL")
public class NapaStores {
	public static final String TABLE_NAME = "NAPA_STORES_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String NAPAId = "NapaId";
	public static final String SECURITY = "Security";
	public static final String CNAME = "Cname";
	public static final String SUBCNAME = "SubCName";
	public static final String ADDRESS = "Address";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* 加盟店ID */
	@Column(name = "NAPAId", length = 64, nullable = false)
	private String NapaId;

	/* セキュアキー  */
	@Column(name = "SECURITY", length = 64, nullable = true)
	private String Security;

	/* 会社名 */
	@Column(name = "CNAME", length = 64, nullable = true)
	private String Cname;

	/* 支店名  */
	@Column(name = "SUBCNAME", length = 64, nullable = true)
	private String SubCName;

	/* 住所  */
	@Column(name = "ADDRESS", length = 64, nullable = true)
	private String Address;

	


	public String getNapaId() {
		return NapaId;
	}




	public void setNapaId(String napaId) {
		NapaId = napaId;
	}




	public String getSecurity() {
		return Security;
	}




	public void setSecurity(String security) {
		Security = security;
	}




	public String getCname() {
		return Cname;
	}




	public void setCname(String cname) {
		Cname = cname;
	}




	public String getSubCName() {
		return SubCName;
	}




	public void setSubCName(String subCName) {
		SubCName = subCName;
	}




	public String getAddress() {
		return Address;
	}




	public void setAddress(String address) {
		Address = address;
	}




	public static String getTableName() {
		return TABLE_NAME;
	}




	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("NapaId");
		sb.append("=");
		sb.append(NapaId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Security");
		sb.append("=");
		sb.append(Security);
		sb.append("\n");
		sb.append("\t");
		sb.append("Cname");
		sb.append("=");
		sb.append(Cname);
		sb.append("\n");
		sb.append("\t");
		sb.append("SubCName");
		sb.append("=");
		sb.append(SubCName);
		sb.append("\n");
		sb.append("\t");
		sb.append("Address");
		sb.append("=");
		sb.append(Address);
		sb.append("\n");
		return sb.toString();
	}

}
