package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * 注文詳細 Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ORDER_DETAIL_TBL")
public class OrderDetail {
	public static final String TABLE_NAME = "ORDER_DETAIL_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String DetailId = "DetailId";
	public static final String OrderId = "OrderId";
	public static final String ItemId = "ItemId";
	public static final String Name = "Name";
	public static final String Type = "Type";
	public static final String PartsCd = "PartsCd";
	public static final String ModelCd = "ModelCd";
	public static final String Quantity = "Quantity";
	public static final String Unit = "Unit";
	public static final String UnitPrice = "UnitPrice";
	public static final String Amount = "Amount";
	public static final String DeliveryDate = "DeliveryDate";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* 注文ID */
	@Column(name = "DETAIL_ID", length = 0, nullable = false)
	private Long detailId;

	@Id
	/* 注文詳細ID */
	@Column(name = "ORDER_ID", length = 0, nullable = false)
	@JoinTable(name = "OrderSheet")
	@JoinColumn(name = "OrderId")
	private Long orderId;

	@Id
	/* 商品 */
	@Column(name = "ITEM_ID", length = 0, nullable = false)
	@JoinTable(name = "Item")
	@JoinColumn(name = "ItemId")
	private Long itemId;

	/* 仕入先 */
	@Column(name = "NAME", length = 64, nullable = false)
	private String name;

	/*  */
	@Column(name = "TYPE", length = 32, nullable = false)
	private String type;

	/*  */
	@Column(name = "PARTS_CD", length = 512, nullable = false)
	private String partsCd;

	/*  */
	@Column(name = "MODEL_CD", length = 32, nullable = true)
	private String modelCd;

	/*  */
	@Column(name = "QUANTITY", length = 0, nullable = true)
	private Integer quantity;

	/*  */
	@Column(name = "UNIT", length = 8, nullable = true)
	private String unit;

	/* 単価 */
	@Column(name = "UNIT_PRICE", length = 0, nullable = true)
	private Money unitPrice;

	/* 数量 */
	@Column(name = "AMOUNT", length = 0, nullable = true)
	private Money amount;

	/*  */
	@Column(name = "DELIVERY_DATE", length = 8, nullable = true)
	private String deliveryDate;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the 注文ID
	 * 
	 * @return the value of 注文ID
	 */
	public Long getDetailId() {
		return detailId;
	}

	/*
	 * Set the value of 注文ID
	 * 
	 * @param detailId the new value for 注文ID
	 */
	public void setDetailId(Long detailId) {
		this.detailId = detailId;
	}

	/*
	 * Get the 注文詳細ID
	 * 
	 * @return the value of 注文詳細ID
	 */
	public Long getOrderId() {
		return orderId;
	}

	/*
	 * Set the value of 注文詳細ID
	 * 
	 * @param orderId the new value for 注文詳細ID
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/*
	 * Get the 商品
	 * 
	 * @return the value of 商品
	 */
	public Long getItemId() {
		return itemId;
	}

	/*
	 * Set the value of 商品
	 * 
	 * @param itemId the new value for 商品
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	/*
	 * Get the 仕入先
	 * 
	 * @return the value of 仕入先
	 */
	public String getName() {
		return name;
	}

	/*
	 * Set the value of 仕入先
	 * 
	 * @param name the new value for 仕入先
	 */
	public void setName(String name) {
		this.name = name;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getType() {
		return type;
	}

	/*
	 * Set the value of
	 * 
	 * @param type the new value for $col.ViewName
	 */
	public void setType(String type) {
		this.type = type;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getPartsCd() {
		return partsCd;
	}

	/*
	 * Set the value of
	 * 
	 * @param partsCd the new value for $col.ViewName
	 */
	public void setPartsCd(String partsCd) {
		this.partsCd = partsCd;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getModelCd() {
		return modelCd;
	}

	/*
	 * Set the value of
	 * 
	 * @param modelCd the new value for $col.ViewName
	 */
	public void setModelCd(String modelCd) {
		this.modelCd = modelCd;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/*
	 * Set the value of
	 * 
	 * @param quantity the new value for $col.ViewName
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getUnit() {
		return unit;
	}

	/*
	 * Set the value of
	 * 
	 * @param unit the new value for $col.ViewName
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/*
	 * Get the 単価
	 * 
	 * @return the value of 単価
	 */
	public Money getUnitPrice() {
		return unitPrice;
	}

	/*
	 * Set the value of 単価
	 * 
	 * @param unitPrice the new value for 単価
	 */
	public void setUnitPrice(Money unitPrice) {
		this.unitPrice = unitPrice;
	}

	/*
	 * Get the 数量
	 * 
	 * @return the value of 数量
	 */
	public Money getAmount() {
		return amount;
	}

	/*
	 * Set the value of 数量
	 * 
	 * @param amount the new value for 数量
	 */
	public void setAmount(Money amount) {
		this.amount = amount;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getDeliveryDate() {
		return deliveryDate;
	}

	/*
	 * Set the value of
	 * 
	 * @param deliveryDate the new value for $col.ViewName
	 */
	public void setDeliveryDate(String deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("DetailId");
		sb.append("=");
		sb.append(detailId);
		sb.append("\n");
		sb.append("\t");
		sb.append("OrderId");
		sb.append("=");
		sb.append(orderId);
		sb.append("\n");
		sb.append("\t");
		sb.append("ItemId");
		sb.append("=");
		sb.append(itemId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Name");
		sb.append("=");
		sb.append(name);
		sb.append("\n");
		sb.append("\t");
		sb.append("Type");
		sb.append("=");
		sb.append(type);
		sb.append("\n");
		sb.append("\t");
		sb.append("PartsCd");
		sb.append("=");
		sb.append(partsCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("ModelCd");
		sb.append("=");
		sb.append(modelCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("Quantity");
		sb.append("=");
		sb.append(quantity);
		sb.append("\n");
		sb.append("\t");
		sb.append("Unit");
		sb.append("=");
		sb.append(unit);
		sb.append("\n");
		sb.append("\t");
		sb.append("UnitPrice");
		sb.append("=");
		sb.append(unitPrice);
		sb.append("\n");
		sb.append("\t");
		sb.append("Amount");
		sb.append("=");
		sb.append(amount);
		sb.append("\n");
		sb.append("\t");
		sb.append("DeliveryDate");
		sb.append("=");
		sb.append(deliveryDate);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
