package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * $table.ViewName Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ORDER_ACCEPT_TBL")
public class OrderAccept {
	public static final String TABLE_NAME = "ORDER_ACCEPT_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String AcceptId = "AcceptId";
	public static final String OrderId = "OrderId";
	public static final String Date = "Date";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "ACCEPT_ID", length = 0, nullable = false)
	private Long acceptId;

	/*  */
	@Column(name = "ORDER_ID", length = 0, nullable = true)
	private Long orderId;

	/*  */
	@Column(name = "DATE", length = 8, nullable = true)
	private String date;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getAcceptId() {
		return acceptId;
	}

	/*
	 * Set the value of
	 * 
	 * @param acceptId the new value for $col.ViewName
	 */
	public void setAcceptId(Long acceptId) {
		this.acceptId = acceptId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getOrderId() {
		return orderId;
	}

	/*
	 * Set the value of
	 * 
	 * @param orderId the new value for $col.ViewName
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getDate() {
		return date;
	}

	/*
	 * Set the value of
	 * 
	 * @param date the new value for $col.ViewName
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("AcceptId");
		sb.append("=");
		sb.append(acceptId);
		sb.append("\n");
		sb.append("\t");
		sb.append("OrderId");
		sb.append("=");
		sb.append(orderId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Date");
		sb.append("=");
		sb.append(date);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
