package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * 注文請求 Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ORDER_REQUIRE_TBL")
public class OrderRequire {
	public static final String TABLE_NAME = "ORDER_REQUIRE_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String RequireId = "RequireId";
	public static final String DetailId = "DetailId";
	public static final String ExciseAmount = "ExciseAmount";
	public static final String AdjustAmount = "AdjustAmount";
	public static final String ShippingCost = "ShippingCost";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "REQUIRE_ID", length = 0, nullable = false)
	private Long requireId;

	/*  */
	@Column(name = "DETAIL_ID", length = 0, nullable = false)
	@JoinTable(name = "OrderDetail")
	@JoinColumn(name = "DetailId")
	private Long detailId;

	/* 消費税 */
	@Column(name = "EXCISE_AMOUNT", length = 0, nullable = true)
	private Money exciseAmount;

	/* 調整金額 */
	@Column(name = "ADJUST_AMOUNT", length = 0, nullable = true)
	private Money adjustAmount;

	/* 送料 */
	@Column(name = "SHIPPING_COST", length = 0, nullable = true)
	private Money shippingCost;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRequireId() {
		return requireId;
	}

	/*
	 * Set the value of
	 * 
	 * @param requireId the new value for $col.ViewName
	 */
	public void setRequireId(Long requireId) {
		this.requireId = requireId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getDetailId() {
		return detailId;
	}

	/*
	 * Set the value of
	 * 
	 * @param detailId the new value for $col.ViewName
	 */
	public void setDetailId(Long detailId) {
		this.detailId = detailId;
	}

	/*
	 * Get the 消費税
	 * 
	 * @return the value of 消費税
	 */
	public Money getExciseAmount() {
		return exciseAmount;
	}

	/*
	 * Set the value of 消費税
	 * 
	 * @param exciseAmount the new value for 消費税
	 */
	public void setExciseAmount(Money exciseAmount) {
		this.exciseAmount = exciseAmount;
	}

	/*
	 * Get the 調整金額
	 * 
	 * @return the value of 調整金額
	 */
	public Money getAdjustAmount() {
		return adjustAmount;
	}

	/*
	 * Set the value of 調整金額
	 * 
	 * @param adjustAmount the new value for 調整金額
	 */
	public void setAdjustAmount(Money adjustAmount) {
		this.adjustAmount = adjustAmount;
	}

	/*
	 * Get the 送料
	 * 
	 * @return the value of 送料
	 */
	public Money getShippingCost() {
		return shippingCost;
	}

	/*
	 * Set the value of 送料
	 * 
	 * @param shippingCost the new value for 送料
	 */
	public void setShippingCost(Money shippingCost) {
		this.shippingCost = shippingCost;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("RequireId");
		sb.append("=");
		sb.append(requireId);
		sb.append("\n");
		sb.append("\t");
		sb.append("DetailId");
		sb.append("=");
		sb.append(detailId);
		sb.append("\n");
		sb.append("\t");
		sb.append("ExciseAmount");
		sb.append("=");
		sb.append(exciseAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("AdjustAmount");
		sb.append("=");
		sb.append(adjustAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("ShippingCost");
		sb.append("=");
		sb.append(shippingCost);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
