package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * 消費税 Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ORDER_EXCISE_TBL")
public class OrderExcise {
	public static final String TABLE_NAME = "ORDER_EXCISE_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String DebtId = "DebtId";
	public static final String OrderCd = "OrderCd";
	public static final String ExciseAmount = "ExciseAmount";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "DEBT_ID", length = 0, nullable = false)
	@JoinTable(name = "Debt")
	@JoinColumn(name = "DebtId")
	private Long debtId;

	/*  */
	@Column(name = "ORDER_CD", length = 0, nullable = false)
	@JoinTable(name = "OrderSheet")
	@JoinColumn(name = "OrderCd")
	private Long orderCd;

	/* 消費税 */
	@Column(name = "EXCISE_AMOUNT", length = 0, nullable = true)
	private Money exciseAmount;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getDebtId() {
		return debtId;
	}

	/*
	 * Set the value of
	 * 
	 * @param debtId the new value for $col.ViewName
	 */
	public void setDebtId(Long debtId) {
		this.debtId = debtId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getOrderCd() {
		return orderCd;
	}

	/*
	 * Set the value of
	 * 
	 * @param orderCd the new value for $col.ViewName
	 */
	public void setOrderCd(Long orderCd) {
		this.orderCd = orderCd;
	}

	/*
	 * Get the 消費税
	 * 
	 * @return the value of 消費税
	 */
	public Money getExciseAmount() {
		return exciseAmount;
	}

	/*
	 * Set the value of 消費税
	 * 
	 * @param exciseAmount the new value for 消費税
	 */
	public void setExciseAmount(Money exciseAmount) {
		this.exciseAmount = exciseAmount;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("DebtId");
		sb.append("=");
		sb.append(debtId);
		sb.append("\n");
		sb.append("\t");
		sb.append("OrderCd");
		sb.append("=");
		sb.append(orderCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("ExciseAmount");
		sb.append("=");
		sb.append(exciseAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
