package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * $table.ViewName Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "PACKING_CURRENCY_TBL")
public class PackingCurrency {
	public static final String TABLE_NAME = "PACKING_CURRENCY_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String Currency = "Currency";
	public static final String OrderNo = "OrderNo";
	public static final String ReceiptNo = "ReceiptNo";
	public static final String Receiver = "Receiver";
	public static final String ShippingDate = "ShippingDate";
	public static final String ShippingCompany = "ShippingCompany";
	public static final String ShippingFrom = "ShippingFrom";
	public static final String ShippingTo = "ShippingTo";
	public static final String IssueDate = "IssueDate";
	public static final String Notify = "Notify";
	public static final String Marks = "Marks";
	public static final String Quantity = "Quantity";
	public static final String Unit = "Unit";
	public static final String Nw = "Nw";
	public static final String Gw = "Gw";
	public static final String M3 = "M3";
	public static final String PalletQuantity = "PalletQuantity";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "CURRENCY", length = 0, nullable = false)
	private Long currency;

	/*  */
	@Column(name = "ORDER_NO", length = 32, nullable = true)
	private String orderNo;

	/*  */
	@Column(name = "RECEIPT_NO", length = 32, nullable = true)
	private String receiptNo;

	/*  */
	@Column(name = "RECEIVER", length = 32, nullable = true)
	private String receiver;

	/*  */
	@Column(name = "SHIPPING_DATE", length = 8, nullable = true)
	private String shippingDate;

	/*  */
	@Column(name = "SHIPPING_COMPANY", length = 64, nullable = true)
	private String shippingCompany;

	/*  */
	@Column(name = "SHIPPING_FROM", length = 64, nullable = true)
	private String shippingFrom;

	/*  */
	@Column(name = "SHIPPING_TO", length = 64, nullable = true)
	private String shippingTo;

	/*  */
	@Column(name = "ISSUE_DATE", length = 8, nullable = true)
	private String issueDate;

	/*  */
	@Column(name = "NOTIFY", length = 64, nullable = true)
	private String notify;

	/*  */
	@Column(name = "MARKS", length = 64, nullable = true)
	private String marks;

	/*  */
	@Column(name = "QUANTITY", length = 0, nullable = true)
	private Integer quantity;

	/*  */
	@Column(name = "UNIT", length = 64, nullable = true)
	private String unit;

	/*  */
	@Column(name = "NW", length = 64, nullable = true)
	private String nw;

	/*  */
	@Column(name = "GW", length = 64, nullable = true)
	private String gw;

	/*  */
	@Column(name = "M3", length = 64, nullable = true)
	private String m3;

	/*  */
	@Column(name = "PALLET_QUANTITY", length = 64, nullable = true)
	private String palletQuantity;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getCurrency() {
		return currency;
	}

	/*
	 * Set the value of
	 * 
	 * @param currency the new value for $col.ViewName
	 */
	public void setCurrency(Long currency) {
		this.currency = currency;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/*
	 * Set the value of
	 * 
	 * @param orderNo the new value for $col.ViewName
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getReceiptNo() {
		return receiptNo;
	}

	/*
	 * Set the value of
	 * 
	 * @param receiptNo the new value for $col.ViewName
	 */
	public void setReceiptNo(String receiptNo) {
		this.receiptNo = receiptNo;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getReceiver() {
		return receiver;
	}

	/*
	 * Set the value of
	 * 
	 * @param receiver the new value for $col.ViewName
	 */
	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getShippingDate() {
		return shippingDate;
	}

	/*
	 * Set the value of
	 * 
	 * @param shippingDate the new value for $col.ViewName
	 */
	public void setShippingDate(String shippingDate) {
		this.shippingDate = shippingDate;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getShippingCompany() {
		return shippingCompany;
	}

	/*
	 * Set the value of
	 * 
	 * @param shippingCompany the new value for $col.ViewName
	 */
	public void setShippingCompany(String shippingCompany) {
		this.shippingCompany = shippingCompany;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getShippingFrom() {
		return shippingFrom;
	}

	/*
	 * Set the value of
	 * 
	 * @param shippingFrom the new value for $col.ViewName
	 */
	public void setShippingFrom(String shippingFrom) {
		this.shippingFrom = shippingFrom;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getShippingTo() {
		return shippingTo;
	}

	/*
	 * Set the value of
	 * 
	 * @param shippingTo the new value for $col.ViewName
	 */
	public void setShippingTo(String shippingTo) {
		this.shippingTo = shippingTo;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getIssueDate() {
		return issueDate;
	}

	/*
	 * Set the value of
	 * 
	 * @param issueDate the new value for $col.ViewName
	 */
	public void setIssueDate(String issueDate) {
		this.issueDate = issueDate;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getNotify() {
		return notify;
	}

	/*
	 * Set the value of
	 * 
	 * @param notify the new value for $col.ViewName
	 */
	public void setNotify(String notify) {
		this.notify = notify;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getMarks() {
		return marks;
	}

	/*
	 * Set the value of
	 * 
	 * @param marks the new value for $col.ViewName
	 */
	public void setMarks(String marks) {
		this.marks = marks;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/*
	 * Set the value of
	 * 
	 * @param quantity the new value for $col.ViewName
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getUnit() {
		return unit;
	}

	/*
	 * Set the value of
	 * 
	 * @param unit the new value for $col.ViewName
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getNw() {
		return nw;
	}

	/*
	 * Set the value of
	 * 
	 * @param nw the new value for $col.ViewName
	 */
	public void setNw(String nw) {
		this.nw = nw;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getGw() {
		return gw;
	}

	/*
	 * Set the value of
	 * 
	 * @param gw the new value for $col.ViewName
	 */
	public void setGw(String gw) {
		this.gw = gw;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getM3() {
		return m3;
	}

	/*
	 * Set the value of
	 * 
	 * @param m3 the new value for $col.ViewName
	 */
	public void setM3(String m3) {
		this.m3 = m3;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getPalletQuantity() {
		return palletQuantity;
	}

	/*
	 * Set the value of
	 * 
	 * @param palletQuantity the new value for $col.ViewName
	 */
	public void setPalletQuantity(String palletQuantity) {
		this.palletQuantity = palletQuantity;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("Currency");
		sb.append("=");
		sb.append(currency);
		sb.append("\n");
		sb.append("\t");
		sb.append("OrderNo");
		sb.append("=");
		sb.append(orderNo);
		sb.append("\n");
		sb.append("\t");
		sb.append("ReceiptNo");
		sb.append("=");
		sb.append(receiptNo);
		sb.append("\n");
		sb.append("\t");
		sb.append("Receiver");
		sb.append("=");
		sb.append(receiver);
		sb.append("\n");
		sb.append("\t");
		sb.append("ShippingDate");
		sb.append("=");
		sb.append(shippingDate);
		sb.append("\n");
		sb.append("\t");
		sb.append("ShippingCompany");
		sb.append("=");
		sb.append(shippingCompany);
		sb.append("\n");
		sb.append("\t");
		sb.append("ShippingFrom");
		sb.append("=");
		sb.append(shippingFrom);
		sb.append("\n");
		sb.append("\t");
		sb.append("ShippingTo");
		sb.append("=");
		sb.append(shippingTo);
		sb.append("\n");
		sb.append("\t");
		sb.append("IssueDate");
		sb.append("=");
		sb.append(issueDate);
		sb.append("\n");
		sb.append("\t");
		sb.append("Notify");
		sb.append("=");
		sb.append(notify);
		sb.append("\n");
		sb.append("\t");
		sb.append("Marks");
		sb.append("=");
		sb.append(marks);
		sb.append("\n");
		sb.append("\t");
		sb.append("Quantity");
		sb.append("=");
		sb.append(quantity);
		sb.append("\n");
		sb.append("\t");
		sb.append("Unit");
		sb.append("=");
		sb.append(unit);
		sb.append("\n");
		sb.append("\t");
		sb.append("Nw");
		sb.append("=");
		sb.append(nw);
		sb.append("\n");
		sb.append("\t");
		sb.append("Gw");
		sb.append("=");
		sb.append(gw);
		sb.append("\n");
		sb.append("\t");
		sb.append("M3");
		sb.append("=");
		sb.append(m3);
		sb.append("\n");
		sb.append("\t");
		sb.append("PalletQuantity");
		sb.append("=");
		sb.append(palletQuantity);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
