package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * $table.ViewName Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "PACKING_LIST_DETAIL_TBL")
public class PackingListDetail {
	public static final String TABLE_NAME = "PACKING_LIST_DETAIL_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String DetailId = "DetailId";
	public static final String PackingListId = "PackingListId";
	public static final String ItemId = "ItemId";
	public static final String Name = "Name";
	public static final String Type = "Type";
	public static final String PartsCd = "PartsCd";
	public static final String ModelCd = "ModelCd";
	public static final String Quantity = "Quantity";
	public static final String Unit = "Unit";
	public static final String UnitPrice = "UnitPrice";
	public static final String Amount = "Amount";
	public static final String Nw = "Nw";
	public static final String Gw = "Gw";
	public static final String M3 = "M3";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "DETAIL_ID", length = 0, nullable = false)
	private Long detailId;

	/*  */
	@Column(name = "PACKING_LIST_ID", length = 0, nullable = false)
	@JoinTable(name = "PackingList")
	@JoinColumn(name = "PackingListId")
	private Long packingListId;

	/*  */
	@Column(name = "ITEM_ID", length = 0, nullable = false)
	@JoinTable(name = "Item")
	@JoinColumn(name = "ItemId")
	private Long itemId;

	/*  */
	@Column(name = "NAME", length = 576, nullable = true)
	private String name;

	/*  */
	@Column(name = "TYPE", length = 64, nullable = true)
	private String type;

	/*  */
	@Column(name = "PARTS_CD", length = 512, nullable = true)
	private String partsCd;

	/*  */
	@Column(name = "MODEL_CD", length = 64, nullable = true)
	private String modelCd;

	/*  */
	@Column(name = "QUANTITY", length = 0, nullable = true)
	private Integer quantity;

	/*  */
	@Column(name = "UNIT", length = 64, nullable = true)
	private String unit;

	/*  */
	@Column(name = "UNIT_PRICE", length = 0, nullable = true)
	private Money unitPrice;

	/*  */
	@Column(name = "AMOUNT", length = 0, nullable = true)
	private Money amount;

	/*  */
	@Column(name = "NW", length = 64, nullable = true)
	private String nw;

	/*  */
	@Column(name = "GW", length = 64, nullable = true)
	private String gw;

	/*  */
	@Column(name = "M3", length = 64, nullable = true)
	private String m3;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getDetailId() {
		return detailId;
	}

	/*
	 * Set the value of
	 * 
	 * @param detailId the new value for $col.ViewName
	 */
	public void setDetailId(Long detailId) {
		this.detailId = detailId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getPackingListId() {
		return packingListId;
	}

	/*
	 * Set the value of
	 * 
	 * @param packingListId the new value for $col.ViewName
	 */
	public void setPackingListId(Long packingListId) {
		this.packingListId = packingListId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getItemId() {
		return itemId;
	}

	/*
	 * Set the value of
	 * 
	 * @param itemId the new value for $col.ViewName
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getName() {
		return name;
	}

	/*
	 * Set the value of
	 * 
	 * @param name the new value for $col.ViewName
	 */
	public void setName(String name) {
		this.name = name;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getType() {
		return type;
	}

	/*
	 * Set the value of
	 * 
	 * @param type the new value for $col.ViewName
	 */
	public void setType(String type) {
		this.type = type;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getPartsCd() {
		return partsCd;
	}

	/*
	 * Set the value of
	 * 
	 * @param partsCd the new value for $col.ViewName
	 */
	public void setPartsCd(String partsCd) {
		this.partsCd = partsCd;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getModelCd() {
		return modelCd;
	}

	/*
	 * Set the value of
	 * 
	 * @param modelCd the new value for $col.ViewName
	 */
	public void setModelCd(String modelCd) {
		this.modelCd = modelCd;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/*
	 * Set the value of
	 * 
	 * @param quantity the new value for $col.ViewName
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getUnit() {
		return unit;
	}

	/*
	 * Set the value of
	 * 
	 * @param unit the new value for $col.ViewName
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Money getUnitPrice() {
		return unitPrice;
	}

	/*
	 * Set the value of
	 * 
	 * @param unitPrice the new value for $col.ViewName
	 */
	public void setUnitPrice(Money unitPrice) {
		this.unitPrice = unitPrice;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Money getAmount() {
		return amount;
	}

	/*
	 * Set the value of
	 * 
	 * @param amount the new value for $col.ViewName
	 */
	public void setAmount(Money amount) {
		this.amount = amount;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getNw() {
		return nw;
	}

	/*
	 * Set the value of
	 * 
	 * @param nw the new value for $col.ViewName
	 */
	public void setNw(String nw) {
		this.nw = nw;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getGw() {
		return gw;
	}

	/*
	 * Set the value of
	 * 
	 * @param gw the new value for $col.ViewName
	 */
	public void setGw(String gw) {
		this.gw = gw;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getM3() {
		return m3;
	}

	/*
	 * Set the value of
	 * 
	 * @param m3 the new value for $col.ViewName
	 */
	public void setM3(String m3) {
		this.m3 = m3;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("DetailId");
		sb.append("=");
		sb.append(detailId);
		sb.append("\n");
		sb.append("\t");
		sb.append("PackingListId");
		sb.append("=");
		sb.append(packingListId);
		sb.append("\n");
		sb.append("\t");
		sb.append("ItemId");
		sb.append("=");
		sb.append(itemId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Name");
		sb.append("=");
		sb.append(name);
		sb.append("\n");
		sb.append("\t");
		sb.append("Type");
		sb.append("=");
		sb.append(type);
		sb.append("\n");
		sb.append("\t");
		sb.append("PartsCd");
		sb.append("=");
		sb.append(partsCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("ModelCd");
		sb.append("=");
		sb.append(modelCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("Quantity");
		sb.append("=");
		sb.append(quantity);
		sb.append("\n");
		sb.append("\t");
		sb.append("Unit");
		sb.append("=");
		sb.append(unit);
		sb.append("\n");
		sb.append("\t");
		sb.append("UnitPrice");
		sb.append("=");
		sb.append(unitPrice);
		sb.append("\n");
		sb.append("\t");
		sb.append("Amount");
		sb.append("=");
		sb.append(amount);
		sb.append("\n");
		sb.append("\t");
		sb.append("Nw");
		sb.append("=");
		sb.append(nw);
		sb.append("\n");
		sb.append("\t");
		sb.append("Gw");
		sb.append("=");
		sb.append(gw);
		sb.append("\n");
		sb.append("\t");
		sb.append("M3");
		sb.append("=");
		sb.append(m3);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
