package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

/*
 * 支払残高 Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "PAYABLE_BALANCE_TBL")
public class PayableBalance {
	public static final String TABLE_NAME = "PAYABLE_BALANCE_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String PayableIｄ = "PayableIｄ";
	public static final String SupplierId = "SupplierId";
	public static final String AccountMonth = "AccountMonth";
	public static final String BalanceMonth = "BalanceMonth";
	public static final String BalanceJpAmount = "BalanceJpAmount";
	public static final String BalanceUsAmount = "BalanceUsAmount";
	public static final String BalanceCnAmount = "BalanceCnAmount";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "PAYABLE_IＤ", length = 0, nullable = false)
	private Long payableIｄ;

	/*  */
	@Column(name = "SUPPLIER_ID", length = 0, nullable = false)
	@JoinTable(name = "Supplier")
	@JoinColumn(name = "SupplierId")
	private Long supplierId;

	/* 残高計算月 */
	@Column(name = "ACCOUNT_MONTH", length = 6, nullable = true)
	private String accountMonth;

	/* 残高年月 */
	@Column(name = "BALANCE_MONTH", length = 6, nullable = true)
	private String balanceMonth;

	/* 残高（日本円） */
	@Column(name = "BALANCE_JP_AMOUNT", length = 0, nullable = true)
	private Long balanceJpAmount;

	/* 残高（ドル） */
	@Column(name = "BALANCE_US_AMOUNT", length = 0, nullable = true)
	private Long balanceUsAmount;

	/* 残高（人民元） */
	@Column(name = "BALANCE_CN_AMOUNT", length = 0, nullable = true)
	private Long balanceCnAmount;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getPayableIｄ() {
		return payableIｄ;
	}

	/*
	 * Set the value of
	 * 
	 * @param payableIｄ the new value for $col.ViewName
	 */
	public void setPayableIｄ(Long payableIｄ) {
		this.payableIｄ = payableIｄ;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getSupplierId() {
		return supplierId;
	}

	/*
	 * Set the value of
	 * 
	 * @param supplierId the new value for $col.ViewName
	 */
	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	/*
	 * Get the 残高計算月
	 * 
	 * @return the value of 残高計算月
	 */
	public String getAccountMonth() {
		return accountMonth;
	}

	/*
	 * Set the value of 残高計算月
	 * 
	 * @param accountMonth the new value for 残高計算月
	 */
	public void setAccountMonth(String accountMonth) {
		this.accountMonth = accountMonth;
	}

	/*
	 * Get the 残高年月
	 * 
	 * @return the value of 残高年月
	 */
	public String getBalanceMonth() {
		return balanceMonth;
	}

	/*
	 * Set the value of 残高年月
	 * 
	 * @param balanceMonth the new value for 残高年月
	 */
	public void setBalanceMonth(String balanceMonth) {
		this.balanceMonth = balanceMonth;
	}

	/*
	 * Get the 残高（日本円）
	 * 
	 * @return the value of 残高（日本円）
	 */
	public Long getBalanceJpAmount() {
		return balanceJpAmount;
	}

	/*
	 * Set the value of 残高（日本円）
	 * 
	 * @param balanceJpAmount the new value for 残高（日本円）
	 */
	public void setBalanceJpAmount(Long balanceJpAmount) {
		this.balanceJpAmount = balanceJpAmount;
	}

	/*
	 * Get the 残高（ドル）
	 * 
	 * @return the value of 残高（ドル）
	 */
	public Long getBalanceUsAmount() {
		return balanceUsAmount;
	}

	/*
	 * Set the value of 残高（ドル）
	 * 
	 * @param balanceUsAmount the new value for 残高（ドル）
	 */
	public void setBalanceUsAmount(Long balanceUsAmount) {
		this.balanceUsAmount = balanceUsAmount;
	}

	/*
	 * Get the 残高（人民元）
	 * 
	 * @return the value of 残高（人民元）
	 */
	public Long getBalanceCnAmount() {
		return balanceCnAmount;
	}

	/*
	 * Set the value of 残高（人民元）
	 * 
	 * @param balanceCnAmount the new value for 残高（人民元）
	 */
	public void setBalanceCnAmount(Long balanceCnAmount) {
		this.balanceCnAmount = balanceCnAmount;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("PayableIｄ");
		sb.append("=");
		sb.append(payableIｄ);
		sb.append("\n");
		sb.append("\t");
		sb.append("SupplierId");
		sb.append("=");
		sb.append(supplierId);
		sb.append("\n");
		sb.append("\t");
		sb.append("AccountMonth");
		sb.append("=");
		sb.append(accountMonth);
		sb.append("\n");
		sb.append("\t");
		sb.append("BalanceMonth");
		sb.append("=");
		sb.append(balanceMonth);
		sb.append("\n");
		sb.append("\t");
		sb.append("BalanceJpAmount");
		sb.append("=");
		sb.append(balanceJpAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("BalanceUsAmount");
		sb.append("=");
		sb.append(balanceUsAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("BalanceCnAmount");
		sb.append("=");
		sb.append(balanceCnAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
