package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * 入荷済み詳細 Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "PAY_MONEY_DETAIL_TBL")
public class PayMoneyDetail {
	public static final String TABLE_NAME = "PAY_MONEY_DETAIL_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String PayDetailId = "PayDetailId";
	public static final String InvoiceDetailId = "InvoiceDetailId";
	public static final String Currency = "Currency";
	public static final String Amount = "Amount";
	public static final String Note = "Note";
	public static final String TradingNo = "TradingNo";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "PAY_DETAIL_ID", length = 0, nullable = false)
	private Long payDetailId;

	/*  */
	@Column(name = "INVOICE_DETAIL_ID", length = 0, nullable = true)
	@JoinTable(name = "InvoiceDetail")
	@JoinColumn(name = "DetailId")
	private Long invoiceDetailId;

	/* 幣種 */
	@Column(name = "CURRENCY", length = 64, nullable = true)
	private String currency;

	/*  */
	@Column(name = "AMOUNT", length = 0, nullable = true)
	private Money amount;

	/* 備考 */
	@Column(name = "NOTE", length = 64, nullable = true)
	private String note;

	/* 取引No. */
	@Column(name = "TRADING_NO", length = 64, nullable = true)
	private String tradingNo;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getPayDetailId() {
		return payDetailId;
	}

	/*
	 * Set the value of
	 * 
	 * @param payDetailId the new value for $col.ViewName
	 */
	public void setPayDetailId(Long payDetailId) {
		this.payDetailId = payDetailId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getInvoiceDetailId() {
		return invoiceDetailId;
	}

	/*
	 * Set the value of
	 * 
	 * @param invoiceDetailId the new value for $col.ViewName
	 */
	public void setInvoiceDetailId(Long invoiceDetailId) {
		this.invoiceDetailId = invoiceDetailId;
	}

	/*
	 * Get the 幣種
	 * 
	 * @return the value of 幣種
	 */
	public String getCurrency() {
		return currency;
	}

	/*
	 * Set the value of 幣種
	 * 
	 * @param currency the new value for 幣種
	 */
	public void setCurrency(String currency) {
		this.currency = currency;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Money getAmount() {
		return amount;
	}

	/*
	 * Set the value of
	 * 
	 * @param amount the new value for $col.ViewName
	 */
	public void setAmount(Money amount) {
		this.amount = amount;
	}

	/*
	 * Get the 備考
	 * 
	 * @return the value of 備考
	 */
	public String getNote() {
		return note;
	}

	/*
	 * Set the value of 備考
	 * 
	 * @param note the new value for 備考
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/*
	 * Get the 取引No.
	 * 
	 * @return the value of 取引No.
	 */
	public String getTradingNo() {
		return tradingNo;
	}

	/*
	 * Set the value of 取引No.
	 * 
	 * @param tradingNo the new value for 取引No.
	 */
	public void setTradingNo(String tradingNo) {
		this.tradingNo = tradingNo;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("PayDetailId");
		sb.append("=");
		sb.append(payDetailId);
		sb.append("\n");
		sb.append("\t");
		sb.append("InvoiceDetailId");
		sb.append("=");
		sb.append(invoiceDetailId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Currency");
		sb.append("=");
		sb.append(currency);
		sb.append("\n");
		sb.append("\t");
		sb.append("Amount");
		sb.append("=");
		sb.append(amount);
		sb.append("\n");
		sb.append("\t");
		sb.append("Note");
		sb.append("=");
		sb.append(note);
		sb.append("\n");
		sb.append("\t");
		sb.append("TradingNo");
		sb.append("=");
		sb.append(tradingNo);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
