package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * 出荷済み一覧 Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "RECEIVE_MONEY_TBL")
public class ReceiveMoney {
	public static final String TABLE_NAME = "RECEIVE_MONEY_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String ReceiveId = "ReceiveId";
	public static final String InvoiceId = "InvoiceId";
	public static final String CustomerIｄ = "CustomerIｄ";
	public static final String Date = "Date";
	public static final String Amount = "Amount";
	public static final String Note = "Note";
	public static final String TradingNo = "TradingNo";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "RECEIVE_ID", length = 0, nullable = false)
	private Long receiveId;

	@Id
	/*  */
	@Column(name = "INVOICE_ID", length = 0, nullable = false)
	@JoinTable(name = "InvoiceSheet")
	@JoinColumn(name = "InvoiceId")
	private Long invoiceId;

	/*  */
	@Column(name = "CUSTOMER_IＤ", length = 0, nullable = false)
	@JoinTable(name = "Customer")
	@JoinColumn(name = "CustomerIｄ")
	private Long customerIｄ;

	/*  */
	@Column(name = "DATE", length = 8, nullable = true)
	private String date;

	/*  */
	@Column(name = "AMOUNT", length = 0, nullable = true)
	private Money amount;

	/*  */
	@Column(name = "NOTE", length = 64, nullable = true)
	private String note;

	/* 取引No. */
	@Column(name = "TRADING_NO", length = 64, nullable = true)
	private String tradingNo;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getReceiveId() {
		return receiveId;
	}

	/*
	 * Set the value of
	 * 
	 * @param receiveId the new value for $col.ViewName
	 */
	public void setReceiveId(Long receiveId) {
		this.receiveId = receiveId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getInvoiceId() {
		return invoiceId;
	}

	/*
	 * Set the value of
	 * 
	 * @param invoiceId the new value for $col.ViewName
	 */
	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getCustomerIｄ() {
		return customerIｄ;
	}

	/*
	 * Set the value of
	 * 
	 * @param customerIｄ the new value for $col.ViewName
	 */
	public void setCustomerIｄ(Long customerIｄ) {
		this.customerIｄ = customerIｄ;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getDate() {
		return date;
	}

	/*
	 * Set the value of
	 * 
	 * @param date the new value for $col.ViewName
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Money getAmount() {
		return amount;
	}

	/*
	 * Set the value of
	 * 
	 * @param amount the new value for $col.ViewName
	 */
	public void setAmount(Money amount) {
		this.amount = amount;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getNote() {
		return note;
	}

	/*
	 * Set the value of
	 * 
	 * @param note the new value for $col.ViewName
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/*
	 * Get the 取引No.
	 * 
	 * @return the value of 取引No.
	 */
	public String getTradingNo() {
		return tradingNo;
	}

	/*
	 * Set the value of 取引No.
	 * 
	 * @param tradingNo the new value for 取引No.
	 */
	public void setTradingNo(String tradingNo) {
		this.tradingNo = tradingNo;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("ReceiveId");
		sb.append("=");
		sb.append(receiveId);
		sb.append("\n");
		sb.append("\t");
		sb.append("InvoiceId");
		sb.append("=");
		sb.append(invoiceId);
		sb.append("\n");
		sb.append("\t");
		sb.append("CustomerIｄ");
		sb.append("=");
		sb.append(customerIｄ);
		sb.append("\n");
		sb.append("\t");
		sb.append("Date");
		sb.append("=");
		sb.append(date);
		sb.append("\n");
		sb.append("\t");
		sb.append("Amount");
		sb.append("=");
		sb.append(amount);
		sb.append("\n");
		sb.append("\t");
		sb.append("Note");
		sb.append("=");
		sb.append(note);
		sb.append("\n");
		sb.append("\t");
		sb.append("TradingNo");
		sb.append("=");
		sb.append(tradingNo);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
