package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * ローラーマスタ Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "ROLERS_TBL")
public class Rolers {
	public static final String TABLE_NAME = "ROLERS_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String RolerId = "RolerId";
	public static final String EnName = "EnName";
	public static final String JpName = "JpName";
	public static final String CnName = "CnName";
	public static final String Priority = "Priority";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* ローラーID */
	@Column(name = "ROLER_ID", length = 0, nullable = false)
	private Long rolerId;

	/* 英語名 */
	@Column(name = "EN_NAME", length = 64, nullable = true)
	private String enName;

	/* 日本語名 */
	@Column(name = "JP_NAME", length = 64, nullable = true)
	private String jpName;

	/* 中国名 */
	@Column(name = "CN_NAME", length = 64, nullable = true)
	private String cnName;

	/* 職務 */
	@Column(name = "PRIORITY", length = 0, nullable = true)
	private Integer priority;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the ローラーID
	 * 
	 * @return the value of ローラーID
	 */
	public Long getRolerId() {
		return rolerId;
	}

	/*
	 * Set the value of ローラーID
	 * 
	 * @param rolerId the new value for ローラーID
	 */
	public void setRolerId(Long rolerId) {
		this.rolerId = rolerId;
	}

	/*
	 * Get the 英語名
	 * 
	 * @return the value of 英語名
	 */
	public String getEnName() {
		return enName;
	}

	/*
	 * Set the value of 英語名
	 * 
	 * @param enName the new value for 英語名
	 */
	public void setEnName(String enName) {
		this.enName = enName;
	}

	/*
	 * Get the 日本語名
	 * 
	 * @return the value of 日本語名
	 */
	public String getJpName() {
		return jpName;
	}

	/*
	 * Set the value of 日本語名
	 * 
	 * @param jpName the new value for 日本語名
	 */
	public void setJpName(String jpName) {
		this.jpName = jpName;
	}

	/*
	 * Get the 中国名
	 * 
	 * @return the value of 中国名
	 */
	public String getCnName() {
		return cnName;
	}

	/*
	 * Set the value of 中国名
	 * 
	 * @param cnName the new value for 中国名
	 */
	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	/*
	 * Get the 職務
	 * 
	 * @return the value of 職務
	 */
	public Integer getPriority() {
		return priority;
	}

	/*
	 * Set the value of 職務
	 * 
	 * @param priority the new value for 職務
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("RolerId");
		sb.append("=");
		sb.append(rolerId);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnName");
		sb.append("=");
		sb.append(enName);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpName");
		sb.append("=");
		sb.append(jpName);
		sb.append("\n");
		sb.append("\t");
		sb.append("CnName");
		sb.append("=");
		sb.append(cnName);
		sb.append("\n");
		sb.append("\t");
		sb.append("Priority");
		sb.append("=");
		sb.append(priority);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
