package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * シーケンス管理 Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "SEQUENCE_CTRL_TBL")
public class SequenceCtrl {
	public static final String TABLE_NAME = "SEQUENCE_CTRL_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String SeqId = "SeqId";
	public static final String SeqType = "SeqType";
	public static final String MinValue = "MinValue";
	public static final String MaxValue = "MaxValue";
	public static final String CurrentValue = "CurrentValue";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* シーケンスID */
	@Column(name = "SEQ_ID", length = 64, nullable = false)
	private String seqId;

	/* シーケンス種類 */
	@Column(name = "SEQ_TYPE", length = 16, nullable = false)
	private String seqType;

	/* 最少値 */
	@Column(name = "MIN_VALUE", length = 0, nullable = false)
	private Long minValue;

	/* 最大値 */
	@Column(name = "MAX_VALUE", length = 0, nullable = false)
	private Long maxValue;

	/* SEQ値 */
	@Column(name = "CURRENT_VALUE", length = 0, nullable = false)
	private Long currentValue;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the シーケンスID
	 * 
	 * @return the value of シーケンスID
	 */
	public String getSeqId() {
		return seqId;
	}

	/*
	 * Set the value of シーケンスID
	 * 
	 * @param seqId the new value for シーケンスID
	 */
	public void setSeqId(String seqId) {
		this.seqId = seqId;
	}

	/*
	 * Get the シーケンス種類
	 * 
	 * @return the value of シーケンス種類
	 */
	public String getSeqType() {
		return seqType;
	}

	/*
	 * Set the value of シーケンス種類
	 * 
	 * @param seqType the new value for シーケンス種類
	 */
	public void setSeqType(String seqType) {
		this.seqType = seqType;
	}

	/*
	 * Get the 最少値
	 * 
	 * @return the value of 最少値
	 */
	public Long getMinValue() {
		return minValue;
	}

	/*
	 * Set the value of 最少値
	 * 
	 * @param minValue the new value for 最少値
	 */
	public void setMinValue(Long minValue) {
		this.minValue = minValue;
	}

	/*
	 * Get the 最大値
	 * 
	 * @return the value of 最大値
	 */
	public Long getMaxValue() {
		return maxValue;
	}

	/*
	 * Set the value of 最大値
	 * 
	 * @param maxValue the new value for 最大値
	 */
	public void setMaxValue(Long maxValue) {
		this.maxValue = maxValue;
	}

	/*
	 * Get the SEQ値
	 * 
	 * @return the value of SEQ値
	 */
	public Long getCurrentValue() {
		return currentValue;
	}

	/*
	 * Set the value of SEQ値
	 * 
	 * @param currentValue the new value for SEQ値
	 */
	public void setCurrentValue(Long currentValue) {
		this.currentValue = currentValue;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("SeqId");
		sb.append("=");
		sb.append(seqId);
		sb.append("\n");
		sb.append("\t");
		sb.append("SeqType");
		sb.append("=");
		sb.append(seqType);
		sb.append("\n");
		sb.append("\t");
		sb.append("MinValue");
		sb.append("=");
		sb.append(minValue);
		sb.append("\n");
		sb.append("\t");
		sb.append("MaxValue");
		sb.append("=");
		sb.append(maxValue);
		sb.append("\n");
		sb.append("\t");
		sb.append("CurrentValue");
		sb.append("=");
		sb.append(currentValue);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
