package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

import com.np.order.Money;

/*
 * $table.ViewName Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "SHIPPING_COST_TBL")
public class ShippingCost {
	public static final String TABLE_NAME = "SHIPPING_COST_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String CostId = "CostId";
	public static final String InvoiceCd = "InvoiceCd";
	public static final String CostAmount = "CostAmount";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/*  */
	@Column(name = "COST_ID", length = 0, nullable = false)
	private Long costId;

	/*  */
	@Column(name = "INVOICE_CD", length = 64, nullable = false)
	@JoinTable(name = "InvoiceSheet")
	@JoinColumn(name = "InvoiceCd")
	private String invoiceCd;

	/*  */
	@Column(name = "COST_AMOUNT", length = 0, nullable = false)
	private Money costAmount;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getCostId() {
		return costId;
	}

	/*
	 * Set the value of
	 * 
	 * @param costId the new value for $col.ViewName
	 */
	public void setCostId(Long costId) {
		this.costId = costId;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getInvoiceCd() {
		return invoiceCd;
	}

	/*
	 * Set the value of
	 * 
	 * @param invoiceCd the new value for $col.ViewName
	 */
	public void setInvoiceCd(String invoiceCd) {
		this.invoiceCd = invoiceCd;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Money getCostAmount() {
		return costAmount;
	}

	/*
	 * Set the value of
	 * 
	 * @param costAmount the new value for $col.ViewName
	 */
	public void setCostAmount(Money costAmount) {
		this.costAmount = costAmount;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("CostId");
		sb.append("=");
		sb.append(costId);
		sb.append("\n");
		sb.append("\t");
		sb.append("InvoiceCd");
		sb.append("=");
		sb.append(invoiceCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("CostAmount");
		sb.append("=");
		sb.append(costAmount);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
