package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

/*
 * ユーザーマスタ Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "USERS_TBL")
public class Users {
	public static final String TABLE_NAME = "USERS_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String UserId = "UserId";
	public static final String Account = "Account";
	public static final String EnName = "EnName";
	public static final String JpName = "JpName";
	public static final String CnName = "CnName";
	public static final String Password = "Password";
	public static final String Role = "Role";
	public static final String Sign = "Sign";
	public static final String Seal = "Seal";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* ID */
	@Column(name = "USER_ID", length = 0, nullable = false)
	private Long userId;

	/* ユーザーID */
	@Column(name = "ACCOUNT", length = 64, nullable = true)
	private String account;

	/* 英語名 */
	@Column(name = "EN_NAME", length = 64, nullable = true)
	private String enName;

	/* 日本語名 */
	@Column(name = "JP_NAME", length = 64, nullable = true)
	private String jpName;

	/* 中国名 */
	@Column(name = "CN_NAME", length = 64, nullable = true)
	private String cnName;

	/* パスワード */
	@Column(name = "PASSWORD", length = 64, nullable = false)
	private String password;

	/* 職務 */
	@Column(name = "ROLE", length = 0, nullable = true)
	@JoinTable(name = "ROLERS_TBL")
	@JoinColumn(name = "ROLER_ID")
	private Long role;

	/* サイン画像 */
	@Column(name = "SIGN", length = 0, nullable = true)
	private byte[] sign;

	/* 印鑑画像 */
	@Column(name = "SEAL", length = 0, nullable = true)
	private byte[] seal;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the ID
	 * 
	 * @return the value of ID
	 */
	public Long getUserId() {
		return userId;
	}

	/*
	 * Set the value of ID
	 * 
	 * @param userId the new value for ID
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/*
	 * Get the ユーザーID
	 * 
	 * @return the value of ユーザーID
	 */
	public String getAccount() {
		return account;
	}

	/*
	 * Set the value of ユーザーID
	 * 
	 * @param account the new value for ユーザーID
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/*
	 * Get the 英語名
	 * 
	 * @return the value of 英語名
	 */
	public String getEnName() {
		return enName;
	}

	/*
	 * Set the value of 英語名
	 * 
	 * @param enName the new value for 英語名
	 */
	public void setEnName(String enName) {
		this.enName = enName;
	}

	/*
	 * Get the 日本語名
	 * 
	 * @return the value of 日本語名
	 */
	public String getJpName() {
		return jpName;
	}

	/*
	 * Set the value of 日本語名
	 * 
	 * @param jpName the new value for 日本語名
	 */
	public void setJpName(String jpName) {
		this.jpName = jpName;
	}

	/*
	 * Get the 中国名
	 * 
	 * @return the value of 中国名
	 */
	public String getCnName() {
		return cnName;
	}

	/*
	 * Set the value of 中国名
	 * 
	 * @param cnName the new value for 中国名
	 */
	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	/*
	 * Get the パスワード
	 * 
	 * @return the value of パスワード
	 */
	public String getPassword() {
		return password;
	}

	/*
	 * Set the value of パスワード
	 * 
	 * @param password the new value for パスワード
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/*
	 * Get the 職務
	 * 
	 * @return the value of 職務
	 */
	public Long getRole() {
		return role;
	}

	/*
	 * Set the value of 職務
	 * 
	 * @param role the new value for 職務
	 */
	public void setRole(Long role) {
		this.role = role;
	}

	/*
	 * Get the サイン画像
	 * 
	 * @return the value of サイン画像
	 */
	public byte[] getSign() {
		return sign;
	}

	/*
	 * Set the value of サイン画像
	 * 
	 * @param sign the new value for サイン画像
	 */
	public void setSign(byte[] sign) {
		this.sign = sign;
	}

	/*
	 * Get the 印鑑画像
	 * 
	 * @return the value of 印鑑画像
	 */
	public byte[] getSeal() {
		return seal;
	}

	/*
	 * Set the value of 印鑑画像
	 * 
	 * @param seal the new value for 印鑑画像
	 */
	public void setSeal(byte[] seal) {
		this.seal = seal;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("UserId");
		sb.append("=");
		sb.append(userId);
		sb.append("\n");
		sb.append("\t");
		sb.append("Account");
		sb.append("=");
		sb.append(account);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnName");
		sb.append("=");
		sb.append(enName);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpName");
		sb.append("=");
		sb.append(jpName);
		sb.append("\n");
		sb.append("\t");
		sb.append("CnName");
		sb.append("=");
		sb.append(cnName);
		sb.append("\n");
		sb.append("\t");
		sb.append("Password");
		sb.append("=");
		sb.append(password);
		sb.append("\n");
		sb.append("\t");
		sb.append("Role");
		sb.append("=");
		sb.append(role);
		sb.append("\n");
		sb.append("\t");
		sb.append("Sign");
		sb.append("=");
		sb.append(sign);
		sb.append("\n");
		sb.append("\t");
		sb.append("Seal");
		sb.append("=");
		sb.append(seal);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
