package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/*
 * 新安情报マスタ Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "XINAN_TBL")
public class Xinan {
	public static final String TABLE_NAME = "XINAN_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String EnName = "EnName";
	public static final String EnShortName = "EnShortName";
	public static final String JpName = "JpName";
	public static final String CnName = "CnName";
	public static final String PostCd = "PostCd";
	public static final String Address1 = "Address1";
	public static final String Address2 = "Address2";
	public static final String Address3 = "Address3";
	public static final String EnAddress1 = "EnAddress1";
	public static final String EnAddress2 = "EnAddress2";
	public static final String EnAddress3 = "EnAddress3";
	public static final String Tel1 = "Tel1";
	public static final String Tel2 = "Tel2";
	public static final String Fax = "Fax";
	public static final String JpnBank = "JpnBank";
	public static final String JpnBranch = "JpnBranch";
	public static final String JpnBankAddress = "JpnBankAddress";
	public static final String JpnAccountType = "JpnAccountType";
	public static final String UsdBank = "UsdBank";
	public static final String UsdBranch = "UsdBranch";
	public static final String UsdBankAddress = "UsdBankAddress";
	public static final String UsdAccountType = "UsdAccountType";
	public static final String RegTime = "RegTime";
	public static final String UpdTime = "UpdTime";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* ユーザーID */
	@Column(name = "EN_NAME", length = 0, nullable = false)
	private Long enName;

	/* 英語名 */
	@Column(name = "EN_SHORT_NAME", length = 64, nullable = true)
	private String enShortName;

	/* 日本語名 */
	@Column(name = "JP_NAME", length = 64, nullable = true)
	private String jpName;

	/* 中国名 */
	@Column(name = "CN_NAME", length = 64, nullable = true)
	private String cnName;

	/*  */
	@Column(name = "POST_CD", length = 8, nullable = true)
	private String postCd;

	/*  */
	@Column(name = "ADDRESS1", length = 64, nullable = true)
	private String address1;

	/*  */
	@Column(name = "ADDRESS2", length = 64, nullable = true)
	private String address2;

	/*  */
	@Column(name = "ADDRESS3", length = 64, nullable = true)
	private String address3;

	/*  */
	@Column(name = "EN_ADDRESS1", length = 64, nullable = true)
	private String enAddress1;

	/*  */
	@Column(name = "EN_ADDRESS2", length = 64, nullable = true)
	private String enAddress2;

	/*  */
	@Column(name = "EN_ADDRESS3", length = 64, nullable = true)
	private String enAddress3;

	/*  */
	@Column(name = "TEL1", length = 16, nullable = true)
	private String tel1;

	/*  */
	@Column(name = "TEL2", length = 16, nullable = true)
	private String tel2;

	/*  */
	@Column(name = "FAX", length = 16, nullable = true)
	private String fax;

	/*  */
	@Column(name = "JPN_BANK", length = 64, nullable = true)
	private String jpnBank;

	/*  */
	@Column(name = "JPN_BRANCH", length = 64, nullable = true)
	private String jpnBranch;

	/*  */
	@Column(name = "JPN_BANK_ADDRESS", length = 64, nullable = true)
	private String jpnBankAddress;

	/*  */
	@Column(name = "JPN_ACCOUNT_TYPE", length = 64, nullable = true)
	private String jpnAccountType;

	/*  */
	@Column(name = "USD_BANK", length = 64, nullable = true)
	private String usdBank;

	/*  */
	@Column(name = "USD_BRANCH", length = 64, nullable = true)
	private String usdBranch;

	/*  */
	@Column(name = "USD_BANK_ADDRESS", length = 64, nullable = true)
	private String usdBankAddress;

	/*  */
	@Column(name = "USD_ACCOUNT_TYPE", length = 64, nullable = true)
	private String usdAccountType;

	/*  */
	@Column(name = "REG_TIME", length = 0, nullable = true)
	private Long regTime;

	/*  */
	@Column(name = "UPD_TIME", length = 0, nullable = true)
	private Long updTime;

	/*
	 * ---------------------- Getter / Setter Methods
	 * ----------------------------
	 */

	/*
	 * Get the ユーザーID
	 * 
	 * @return the value of ユーザーID
	 */
	public Long getEnName() {
		return enName;
	}

	/*
	 * Set the value of ユーザーID
	 * 
	 * @param enName the new value for ユーザーID
	 */
	public void setEnName(Long enName) {
		this.enName = enName;
	}

	/*
	 * Get the 英語名
	 * 
	 * @return the value of 英語名
	 */
	public String getEnShortName() {
		return enShortName;
	}

	/*
	 * Set the value of 英語名
	 * 
	 * @param enShortName the new value for 英語名
	 */
	public void setEnShortName(String enShortName) {
		this.enShortName = enShortName;
	}

	/*
	 * Get the 日本語名
	 * 
	 * @return the value of 日本語名
	 */
	public String getJpName() {
		return jpName;
	}

	/*
	 * Set the value of 日本語名
	 * 
	 * @param jpName the new value for 日本語名
	 */
	public void setJpName(String jpName) {
		this.jpName = jpName;
	}

	/*
	 * Get the 中国名
	 * 
	 * @return the value of 中国名
	 */
	public String getCnName() {
		return cnName;
	}

	/*
	 * Set the value of 中国名
	 * 
	 * @param cnName the new value for 中国名
	 */
	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getPostCd() {
		return postCd;
	}

	/*
	 * Set the value of
	 * 
	 * @param postCd the new value for $col.ViewName
	 */
	public void setPostCd(String postCd) {
		this.postCd = postCd;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getAddress1() {
		return address1;
	}

	/*
	 * Set the value of
	 * 
	 * @param address1 the new value for $col.ViewName
	 */
	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getAddress2() {
		return address2;
	}

	/*
	 * Set the value of
	 * 
	 * @param address2 the new value for $col.ViewName
	 */
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getAddress3() {
		return address3;
	}

	/*
	 * Set the value of
	 * 
	 * @param address3 the new value for $col.ViewName
	 */
	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getEnAddress1() {
		return enAddress1;
	}

	/*
	 * Set the value of
	 * 
	 * @param enAddress1 the new value for $col.ViewName
	 */
	public void setEnAddress1(String enAddress1) {
		this.enAddress1 = enAddress1;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getEnAddress2() {
		return enAddress2;
	}

	/*
	 * Set the value of
	 * 
	 * @param enAddress2 the new value for $col.ViewName
	 */
	public void setEnAddress2(String enAddress2) {
		this.enAddress2 = enAddress2;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getEnAddress3() {
		return enAddress3;
	}

	/*
	 * Set the value of
	 * 
	 * @param enAddress3 the new value for $col.ViewName
	 */
	public void setEnAddress3(String enAddress3) {
		this.enAddress3 = enAddress3;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getTel1() {
		return tel1;
	}

	/*
	 * Set the value of
	 * 
	 * @param tel1 the new value for $col.ViewName
	 */
	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getTel2() {
		return tel2;
	}

	/*
	 * Set the value of
	 * 
	 * @param tel2 the new value for $col.ViewName
	 */
	public void setTel2(String tel2) {
		this.tel2 = tel2;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getFax() {
		return fax;
	}

	/*
	 * Set the value of
	 * 
	 * @param fax the new value for $col.ViewName
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getJpnBank() {
		return jpnBank;
	}

	/*
	 * Set the value of
	 * 
	 * @param jpnBank the new value for $col.ViewName
	 */
	public void setJpnBank(String jpnBank) {
		this.jpnBank = jpnBank;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getJpnBranch() {
		return jpnBranch;
	}

	/*
	 * Set the value of
	 * 
	 * @param jpnBranch the new value for $col.ViewName
	 */
	public void setJpnBranch(String jpnBranch) {
		this.jpnBranch = jpnBranch;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getJpnBankAddress() {
		return jpnBankAddress;
	}

	/*
	 * Set the value of
	 * 
	 * @param jpnBankAddress the new value for $col.ViewName
	 */
	public void setJpnBankAddress(String jpnBankAddress) {
		this.jpnBankAddress = jpnBankAddress;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getJpnAccountType() {
		return jpnAccountType;
	}

	/*
	 * Set the value of
	 * 
	 * @param jpnAccountType the new value for $col.ViewName
	 */
	public void setJpnAccountType(String jpnAccountType) {
		this.jpnAccountType = jpnAccountType;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getUsdBank() {
		return usdBank;
	}

	/*
	 * Set the value of
	 * 
	 * @param usdBank the new value for $col.ViewName
	 */
	public void setUsdBank(String usdBank) {
		this.usdBank = usdBank;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getUsdBranch() {
		return usdBranch;
	}

	/*
	 * Set the value of
	 * 
	 * @param usdBranch the new value for $col.ViewName
	 */
	public void setUsdBranch(String usdBranch) {
		this.usdBranch = usdBranch;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getUsdBankAddress() {
		return usdBankAddress;
	}

	/*
	 * Set the value of
	 * 
	 * @param usdBankAddress the new value for $col.ViewName
	 */
	public void setUsdBankAddress(String usdBankAddress) {
		this.usdBankAddress = usdBankAddress;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public String getUsdAccountType() {
		return usdAccountType;
	}

	/*
	 * Set the value of
	 * 
	 * @param usdAccountType the new value for $col.ViewName
	 */
	public void setUsdAccountType(String usdAccountType) {
		this.usdAccountType = usdAccountType;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getRegTime() {
		return regTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param regTime the new value for $col.ViewName
	 */
	public void setRegTime(Long regTime) {
		this.regTime = regTime;
	}

	/*
	 * Get the
	 * 
	 * @return the value of $col.ViewName
	 */
	public Long getUpdTime() {
		return updTime;
	}

	/*
	 * Set the value of
	 * 
	 * @param updTime the new value for $col.ViewName
	 */
	public void setUpdTime(Long updTime) {
		this.updTime = updTime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("EnName");
		sb.append("=");
		sb.append(enName);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnShortName");
		sb.append("=");
		sb.append(enShortName);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpName");
		sb.append("=");
		sb.append(jpName);
		sb.append("\n");
		sb.append("\t");
		sb.append("CnName");
		sb.append("=");
		sb.append(cnName);
		sb.append("\n");
		sb.append("\t");
		sb.append("PostCd");
		sb.append("=");
		sb.append(postCd);
		sb.append("\n");
		sb.append("\t");
		sb.append("Address1");
		sb.append("=");
		sb.append(address1);
		sb.append("\n");
		sb.append("\t");
		sb.append("Address2");
		sb.append("=");
		sb.append(address2);
		sb.append("\n");
		sb.append("\t");
		sb.append("Address3");
		sb.append("=");
		sb.append(address3);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnAddress1");
		sb.append("=");
		sb.append(enAddress1);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnAddress2");
		sb.append("=");
		sb.append(enAddress2);
		sb.append("\n");
		sb.append("\t");
		sb.append("EnAddress3");
		sb.append("=");
		sb.append(enAddress3);
		sb.append("\n");
		sb.append("\t");
		sb.append("Tel1");
		sb.append("=");
		sb.append(tel1);
		sb.append("\n");
		sb.append("\t");
		sb.append("Tel2");
		sb.append("=");
		sb.append(tel2);
		sb.append("\n");
		sb.append("\t");
		sb.append("Fax");
		sb.append("=");
		sb.append(fax);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpnBank");
		sb.append("=");
		sb.append(jpnBank);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpnBranch");
		sb.append("=");
		sb.append(jpnBranch);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpnBankAddress");
		sb.append("=");
		sb.append(jpnBankAddress);
		sb.append("\n");
		sb.append("\t");
		sb.append("JpnAccountType");
		sb.append("=");
		sb.append(jpnAccountType);
		sb.append("\n");
		sb.append("\t");
		sb.append("UsdBank");
		sb.append("=");
		sb.append(usdBank);
		sb.append("\n");
		sb.append("\t");
		sb.append("UsdBranch");
		sb.append("=");
		sb.append(usdBranch);
		sb.append("\n");
		sb.append("\t");
		sb.append("UsdBankAddress");
		sb.append("=");
		sb.append(usdBankAddress);
		sb.append("\n");
		sb.append("\t");
		sb.append("UsdAccountType");
		sb.append("=");
		sb.append(usdAccountType);
		sb.append("\n");
		sb.append("\t");
		sb.append("RegTime");
		sb.append("=");
		sb.append(regTime);
		sb.append("\n");
		sb.append("\t");
		sb.append("UpdTime");
		sb.append("=");
		sb.append(updTime);
		sb.append("\n");
		return sb.toString();
	}

}
